# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags_colors',
        ),
    ]
