# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0011_userstory_tribe_gig'),
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='tags',
        ),
    ]
