# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20151104_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['project', 'created_date', 'ref'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
    ]
