# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_remove_issue_watchers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['project', '-id'], 'verbose_name': 'issue', 'verbose_name_plural': 'issues'},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='tags',
        ),
    ]
